# RT-Thread building script for component

from building import *

Import('rtconfig')

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd]
ASFLAGS = ''

group = DefineGroup('BLDRV', src, depend = [''], CPPPATH = CPPPATH, ASFLAGS = ASFLAGS)

Return('group')
