Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = []

if GetDepend('AIC_USING_CAMERA'):
    CPPPATH.append(cwd)

if GetDepend('AIC_USING_CAMERA_OV7670'):
    src += Glob('ov7670/*.c')

if GetDepend('AIC_USING_CAMERA_OV5640'):
    src += Glob('ov5640/*.c')

if GetDepend('AIC_USING_CAMERA_OV2659'):
    src += Glob('ov2659/*.c')

if GetDepend('AIC_USING_CAMERA_OV2640'):
    src += Glob('ov2640/*.c')

if GetDepend('AIC_USING_CAMERA_GM7150'):
    src += Glob('gm7150/*.c')

if GetDepend('AIC_USING_CAMERA_TP2825'):
    src += Glob('tp2825b/tp2825bx.c')

LOCAL_CCFLAGS = ''
# LOCAL_CCFLAGS += ' -O0'

group = DefineGroup('ov5640', src, depend = [''], CPPPATH = CPPPATH, LOCAL_CCFLAGS=LOCAL_CCFLAGS)

Return('group')
