Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = []
src = []
if GetDepend('AIC_DCE_DRV_TEST') and GetDepend('KERNEL_BAREMETAL'):
    src = Glob('*.c')

group = DefineGroup('test-dce', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
